/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * labs-api
 * 
This project provides a reference Python API built using FastAPI, the 
aim of the project is:

- To maintain a good know source of habits
- Demonstrate how applications are meant to be put together at Anomaly
- Democratize design of robust API


 * OpenAPI spec version: 0.1.0
 */

/**
 * Provides a health check response with a timestamp

All cloud native applications should provide a health check endpoint
for loadbalancers to see if the application is healthy
 */
export interface HealthCheckResponse {
  all_ok?: boolean;
  db_ok?: boolean;
  queue_ok?: boolean;
  log_ok?: boolean;
  timestamp?: string;
}
