/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * labs-api
 * 
This project provides a reference Python API built using FastAPI, the 
aim of the project is:

- To maintain a good know source of habits
- Demonstrate how applications are meant to be put together at Anomaly
- Democratize design of robust API


 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic base model for applications

This class is used to define the base model for all schema
that we use in the Application, it configures pydantic to
translate between camcelCase and snake_case for the JSON
amongst other default settings.
 */
export interface OTPTriggerSMSRequest {
  mobileNumber: string;
}
